Exception: STATUS_ACCESS_VIOLATION at rip=00382E9AA18
rax=0000000382FF8D80 rbx=0000000000000000 rcx=0000000000000000
rdx=000006FFFFAD9C08 rsi=000006FFFFAFEEA0 rdi=000006FFFFE680F0
r8 =0000000000000000 r9 =00000005D6133013 r10=8080808080808080
r11=000006FFFFADD568 r12=000006FFFFAE1818 r13=00000005D6131201
r14=000006FFFFF77598 r15=000006FFFFAFEEA0
rbp=00000000FFFFC4C0 rsp=00000000FFFFC410
program=C:\cygwin64\bin\python3.6m.exe, pid 13096, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFC4C0  00382E9AA18 (005D613300F, 00000000000, 00000000000, 000FFFFC4E0)
000FFFFC4C0  005D6131072 (00300000000, 000000018A7, 00000000000, 00000000000)
000FFFFC4F0  005D613122E (6FFFFE680F0, 6FFFFC666D0, 6FFFFA405F0, 6FFFFFF7510)
00000000000  00382EE0A69 (6FFFFC73ED0, 6FFFFAE1818, 00382EE1213, 00000000000)
00000000001  00382F52851 (00382ED2322, 6FFFFF6BE20, 6FFFFF6BE38, 000FFFFFFFF)
00600001080  00382F546D4 (00300000000, 6FFFFC760C0, 00200000007, 6FFFFF7A0F0)
6FFFFF77590  00382F523AC (6FFFFEEB120, 6FFFFF5F658, 000FFFFCAEC, 00000000000)
6FFFFE861F0  00382F52981 (6FFFFEEC3E8, 6FFFFE861F0, 00382F6E06D, 6FFFFF512D0)
6FFFFE861F0  00382F7A4E3 (000FFFFC968, 00000000000, 00382ED436A, 000FFFFCAEC)
6FFFFE861F0  00382F7C39F (6FFFFEF8998, 0018020F7D8, 00000000000, 000FFFFCAEC)
000FFFFCAEC  00382F7C5F0 (0018005B61F, 0038307705C, 00100000000, 006000004B0)
000FFFFCAEC  00382F7CDDC (0018020FAC0, 00383076FC8, 00180144890, 001803276D0)
00000000001  00382F92651 (0018018EDCC, 0018005CD74, 00180326C00, 00180261320)
006000004D8  001004018DB (00000000020, 30001010000FF00, 00180049DAA, 00180048DF0)
000FFFFCCD0  00180049E16 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  00180047973 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace (more stack frames may be present)
